// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLD6i8RZ5zXRForLZIWGrwRFAPWGSe6E',
    appId: '1:402357039635:web:274ced9dc087ab108a05e6',
    messagingSenderId: '402357039635',
    projectId: 'new-threadnest',
    authDomain: 'new-threadnest.firebaseapp.com',
    storageBucket: 'new-threadnest.firebasestorage.app',
    measurementId: 'G-20LS9PLQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKNHIHcl_aRn8Wi53DaMq8XxpGh7lVGuY',
    appId: '1:402357039635:android:484d5483d5453ba78a05e6',
    messagingSenderId: '402357039635',
    projectId: 'new-threadnest',
    storageBucket: 'new-threadnest.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLD6i8RZ5zXRForLZIWGrwRFAPWGSe6E',
    appId: '1:402357039635:web:86c0d261c0b9dc8c8a05e6',
    messagingSenderId: '402357039635',
    projectId: 'new-threadnest',
    authDomain: 'new-threadnest.firebaseapp.com',
    storageBucket: 'new-threadnest.firebasestorage.app',
    measurementId: 'G-VXC2P265CN',
  );

}